### ISSUE TITLE
Unexpected value  'Axis in  xxx/node_modules/viser-ng/src/components/index.ts' declared by the module 'ViserModule in xxx/node_modules/viser-ng/src/module.ts'. Please add a @Pipe/@Directive/@Component annotation.

### ISSUE THREAD

**Issue by lhqmcy** [linhuiw/viser-ng-demo#1]
when i use viser-ng in my app(create with angular-cli),it works ok on development,but when i want to build the app, i got the error(just as the title).

I tried to down the demo(https://github.com/linhuiw/viser-ng-demo) ,and build it. I got the same error!

I have no idea,what's wrong with this ?

Here is some configs in package.json : 

`"dependencies": {`
    `"@angular/animations": "^5.0.0",`
    `"@angular/common": "^5.0.0",`
   ` "@angular/compiler": "^5.0.0",`
   ` "@angular/core": "^5.0.0",`
    `"@angular/forms": "^5.0.0",`
    `"@angular/http": "^5.0.0",`
   `"@angular/platform-browser": "^5.0.0",`
    `"@angular/platform-browser-dynamic": "^5.0.0",`
    `"@angular/router": "^5.0.0",`
   ` "classlist.js": "^1.1.20150312",`
   ` "core-js": "^2.4.1",`
   ` "ng-zorro-antd": "^0.6.8",`
    `"rxjs": "^5.5.2",`
    `"viser-ng": "^2.0.6",`
    `"web-animations-js": "^2.3.1",`
    `"zone.js": "^0.8.14"`
  `},`
 ` "devDependencies": {`
   ` "@angular/cli": "1.6.1",`
    `"@angular/compiler-cli": "^5.0.0",`
    `"@angular/language-service": "^5.0.0",`
    `"@types/jasmine": "~2.5.53",`
    `"@types/jasminewd2": "~2.0.2",`
    `"@types/node": "~6.0.60",`
    `"codelyzer": "^4.0.1",`
    `"jasmine-core": "~2.6.2",`
    `"jasmine-spec-reporter": "~4.1.0",`
    `"karma": "~1.7.0",`
    `"karma-chrome-launcher": "~2.1.1",`
    `"karma-cli": "~1.0.1",`
    `"karma-coverage-istanbul-reporter": "^1.2.1",`
    `"karma-jasmine": "~1.1.0",`
    `"karma-jasmine-html-reporter": "^0.2.2",`
    `"protractor": "~5.1.2",`
    `"ts-node": "~3.2.0",`
    `"tslint": "~5.7.0",`
    `"typescript": "~2.4.2"`
 ` }`

**Comment by linhuiw** [comment]
Fixed

**Comment by lhqmcy** [comment]
Ok,I will try!
