### ISSUE TITLE
ng build --prod 编译后的文件无法正常工作

### ISSUE THREAD

**Issue by hmukan** [linhuiw/viser-ng-demo#2]
您好，ng build 的方式编译部署nginx后，工作正常。
但是通过ng build --prod的方式编译部署nginx后，不能正常工作，页面不能显示，console的提示错误：
ERROR TypeError: Cannot set property 'container' of undefined(…)

**Comment by linhuiw** [comment]
本地可以正常工作么?

部署 nginx 应该跟代码正确性没有关系.

**Comment by hmukan** [comment]
本地也不能正常工作。 你本地能重现这个问题吗？

是部署在本地的nginx，nginx只作为静态文件服务。

所以我怀疑构建后的文件是否正常？

**Comment by linhuiw** [comment]
是未编译代码正常， 编译后的代码无法运行了么？

我拿这个仓库试试看。

**Comment by hmukan** [comment]
是的，这个仓库npm start 和ng build编译后部署到nginx方式都没问题，就是ng build --prod方式问题。viser-ng更新到2.2.2版本ng build --prod也是一样有问题的。

**Comment by linhuiw** [comment]
Fixed https://github.com/viserjs/viser/pull/157
